version: '3'
services:
  soulencryption-sales-site:
    container_name: soulencryption-sales-site
    build:
      dockerfile: Dockerfile
      context: .
      target: runner
    ports:
      - "3000:3000"
  # web-server:
  #   container_name: web-server
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #     target: web-server
  #   ports:
  #     - "80:80"
  #     - "443:443"